version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: "always"
    volumes:
      - 'mongodb-data:/data/db'
    ports:
      - '27017:27017'
    command: mongod
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    restart: "always"
    hostname: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
      RABBITMQ_DEFAULT_VHOST: 'vhost'
    ports:
      - '15672:15672'
      - '5672:5672'
volumes:
  mongodb-data: {}